FROM node:18-alpine AS builder

WORKDIR /app

# Установка зависимостей
COPY package*.json ./
RUN npm install

# Копирование кода и сборка
COPY . .
RUN npm run build

# Production образ
FROM node:18-alpine

WORKDIR /app

# Копирование необходимых файлов из builder
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package*.json ./

EXPOSE 3030

ENV PORT=3030

CMD ["npm", "start"]
